<?php
namespace App;
class Application extends \Letid\Http\Request
{
    protected $page = array(
        'home'=>array(
            'Class'=>'home',
            'Method'=>'home',
            'Menu'=>'Home'
        ),
        'about-us'=>array(
        	'Method'=>'aboutUs',
        	'Menu'=>'About us'
        ),
        'terms'=>array(
        	'Method'=>'terms',
        	'Menu'=>'Terms'
        ),
        'privacy'=>array(
        	'Method'=>'privacy',
        	'Menu'=>'Privacy'
        ),
        'redirect'=>array(
            'Menu'=>'Redirect',
            'Link'=>'http://www.google.com',
            'Type'=>false
        ),
        'login'=>array(
            'Class'=>'user',
            'Method'=>'login',
            'Menu'=>'Login',
            'Type'=>'user',
            'Auth'=>array('age'=>12)
        ),
        'forgot-password'=>array(
            'Class'=>'user',
            'Method'=>'forgotPassword',
            'Menu'=>'Forgot password',
            'Type'=>'user'
        ),
        'register'=>array(
            'Class'=>'user',
            'Method'=>'register',
            'Menu'=>'Register',
            'Type'=>'user'
        ),
        'music'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>30),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        ),
        'music9'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>9),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        ),
        'music8'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>8),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        ),
        'music3'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>30),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        ),
        'music4'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>30),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        ),
        'music5'=>array(
            'Class'=>'music',
            'Auth'=>array('age'=>30),
            'album'=>array(
                'Method'=>'album'
            ),
            'artist'=>array(
                'Method'=>'artist'
            )
        )
    );
    protected $config = array(
        'version'=>'1.0.9.1'
    );
}
